In [1]:
# Import Dependencies
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
DV_crime_df = pd.read_csv("../Violence_data/DV_crime.csv")
DV_crime_df.head()

,INCIDENT_ID,OFFENSE_ID,OFFENSE_CODE,OFFENSE_CODE_EXTENSION,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,FIRST_OCCURRENCE_DATE,LAST_OCCURRENCE_DATE,REPORTED_DATE,INCIDENT_ADDRESS,GEO_X,GEO_Y,GEO_LON,GEO_LAT,DISTRICT_ID,PRECINCT_ID,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC
0,2018869789,2018869789239900,2399,0,theft-other,larceny,12/27/2018 3:58:00 PM,NaN,12/27/2018 4:51:00 PM,2681 N HANOVER CT,3178210.0,1700715.0,-104.866156,39.755561,5,512,stapleton,1,0
1,2015664356,2015664356544100,5441,0,traffic-accident,traffic-accident,11/13/2015 7:45:00 AM,NaN,11/13/2015 8:38:00 AM,4100 BLOCK W COLFAX AVE,3129148.0,1694748.0,-105.040760,39.739991,1,122,west-colfax,0,1
2,20176005213,20176005213239901,2399,1,theft-bicycle,larceny,6/8/2017 1:15:00 PM,6/8/2017 5:15:00 PM,6/12/2017 8:44:00 AM,1705 17TH ST,3140790.0,1699792.0,-104.999264,39.753669,6,612,union-station,1,0
3,20196012240,20196012240230800,2308,0,theft-from-bldg,larceny,12/7/2019 1:07:00 PM,12/7/2019 6:30:00 PM,12/9/2019 1:35:00 PM,1350 N IRVING ST,3132400.0,1694088.0,-105.029208,39.738134,1,122,west-colfax,1,0
4,2018861883,2018861883501600,5016,0,violation-of-restraining-order,all-other-crimes,12/22/2018 8:15:00 PM,12/22/2018 8:31:00 PM,12/22/2018 10:00:00 PM,13625 E RANDOLPH PL,3188580.0,1716158.0,-104.828868,39.797750,5,521,montbello,1,0

In [3]:
DV_crime_df.columns

Index(['INCIDENT_ID', 'OFFENSE_ID', 'OFFENSE_CODE', 'OFFENSE_CODE_EXTENSION',
       'OFFENSE_TYPE_ID', 'OFFENSE_CATEGORY_ID', 'FIRST_OCCURRENCE_DATE',
       'LAST_OCCURRENCE_DATE', 'REPORTED_DATE', 'INCIDENT_ADDRESS', 'GEO_X',
       'GEO_Y', 'GEO_LON', 'GEO_LAT', 'DISTRICT_ID', 'PRECINCT_ID',
       'NEIGHBORHOOD_ID', 'IS_CRIME', 'IS_TRAFFIC'],
      dtype='object')

In [4]:
DV_crime_df = DV_crime_df.loc[:, ["INCIDENT_ID", "OFFENSE_TYPE_ID", "OFFENSE_CATEGORY_ID", "GEO_LON", "GEO_LAT"]]

In [5]:
DV_crime_df.head()

,INCIDENT_ID,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,GEO_LON,GEO_LAT
0,2018869789,theft-other,larceny,-104.866156,39.755561
1,2015664356,traffic-accident,traffic-accident,-105.040760,39.739991
2,20176005213,theft-bicycle,larceny,-104.999264,39.753669
3,20196012240,theft-from-bldg,larceny,-105.029208,39.738134
4,2018861883,violation-of-restraining-order,all-other-crimes,-104.828868,39.797750

In [6]:
DV_crime_df.dtypes

INCIDENT_ID              int64
OFFENSE_TYPE_ID         object
OFFENSE_CATEGORY_ID     object
GEO_LON                float64
GEO_LAT                float64
dtype: object

In [7]:
SF_crime_df = pd.read_csv("../Violence_data/SF_crime.csv")
SF_crime_df.head()

,IncidntNum,Category,Descript,DayOfWeek,Date,Time,PdDistrict,Resolution,Address,X,Y,Location,PdId
0,120058272,WEAPON LAWS,POSS OF PROHIBITED WEAPON,Friday,01/29/2016 12:00:00 AM,11:00,SOUTHERN,"ARREST, BOOKED",800 Block of BRYANT ST,-122.403405,37.775421,"(37.775420706711, -122.403404791479)",12005827212120
1,120058272,WEAPON LAWS,"FIREARM, LOADED, IN VEHICLE, POSSESSION OR USE",Friday,01/29/2016 12:00:00 AM,11:00,SOUTHERN,"ARREST, BOOKED",800 Block of BRYANT ST,-122.403405,37.775421,"(37.775420706711, -122.403404791479)",12005827212168
2,141059263,WARRANTS,WARRANT ARREST,Monday,04/25/2016 12:00:00 AM,14:59,BAYVIEW,"ARREST, BOOKED",KEITH ST / SHAFTER AV,-122.388856,37.729981,"(37.7299809672996, -122.388856204292)",14105926363010
3,160013662,NON-CRIMINAL,LOST PROPERTY,Tuesday,01/05/2016 12:00:00 AM,23:50,TENDERLOIN,NONE,JONES ST / OFARRELL ST,-122.412971,37.785788,"(37.7857883766888, -122.412970537591)",16001366271000
4,160002740,NON-CRIMINAL,LOST PROPERTY,Friday,01/01/2016 12:00:00 AM,00:30,MISSION,NONE,16TH ST / MISSION ST,-122.419672,37.765050,"(37.7650501214668, -122.419671780296)",16000274071000

In [8]:
SF_crime_df = SF_crime_df.loc[:, ["IncidntNum", "Category","Descript", "X", "Y"]]

In [9]:
SF_crime_df.head()

,IncidntNum,Category,Descript,X,Y
0,120058272,WEAPON LAWS,POSS OF PROHIBITED WEAPON,-122.403405,37.775421
1,120058272,WEAPON LAWS,"FIREARM, LOADED, IN VEHICLE, POSSESSION OR USE",-122.403405,37.775421
2,141059263,WARRANTS,WARRANT ARREST,-122.388856,37.729981
3,160013662,NON-CRIMINAL,LOST PROPERTY,-122.412971,37.785788
4,160002740,NON-CRIMINAL,LOST PROPERTY,-122.419672,37.765050

In [10]:
SF_crime_df.dtypes

IncidntNum      int64
Category       object
Descript       object
X             float64
Y             float64
dtype: object

In [11]:
%load_ext sql

In [12]:
%sql postgresql://postgres:1379@localhost:5432/project_2

In [13]:
%sql CREATE TABLE SF_crime (IncidntNum int, Category varchar(200), descript varchar(200), X float, Y float);

 * postgresql://postgres:***@localhost:5432/project_2
(psycopg2.errors.DuplicateTable) relation "sf_crime" already exists

[SQL: CREATE TABLE SF_crime (IncidntNum int, Category varchar(200), descript varchar(200), X float, Y float);]
(Background on this error at: http://sqlalche.me/e/f405)

In [14]:
%sql CREATE TABLE DV_crime (INCIDENT_ID int, OFFENSE_TYPE_ID varchar(200), OFFENSE_CATEGORY_ID varchar(200), GEO_LON float, GEO_LAT float);

 * postgresql://postgres:***@localhost:5432/project_2
(psycopg2.errors.DuplicateTable) relation "dv_crime" already exists

[SQL: CREATE TABLE DV_crime (INCIDENT_ID int, OFFENSE_TYPE_ID varchar(200), OFFENSE_CATEGORY_ID varchar(200), GEO_LON float, GEO_LAT float);]
(Background on this error at: http://sqlalche.me/e/f405)

In [15]:
DV_crime_df.OFFENSE_CATEGORY_ID = DV_crime_df.OFFENSE_CATEGORY_ID.astype(str)
DV_crime_df.OFFENSE_TYPE_ID = DV_crime_df.OFFENSE_TYPE_ID.astype(str)
SF_crime_df.Category = SF_crime_df.Category.astype(str)
SF_crime_df.Descript = SF_crime_df.Descript.astype(str)


SF_crime_df.to_csv("sf_data.csv", index = False)

In [16]:
DV_crime_df.to_csv("dv_data.csv", index = False)